/**
 * Quiz Entity
 * 
 * Purpose: Represents a quiz/trivia game session with multiple rounds and teams.
 * 
 * Features:
 * - Score normalization: Can convert different round scales to a standard scale
 * - Visual gradients: Can enable/disable color gradients for team rankings
 * - Cascading deletes: Deleting a quiz removes all associated rounds and team participations
 * 
 * Relationships:
 * - One quiz has many rounds (questions/categories)
 * - One quiz has many team participations (via TeamQuiz junction table)
 * 
 * Database Table: "quiz"
 */

import { Entity, PrimaryGeneratedColumn, Column, OneToMany, CreateDateColumn } from "typeorm";
import { Round } from "./Round";
import { TeamQuiz } from "./TeamQuiz";

@Entity()
export class Quiz {
    /**
     * Primary key - unique identifier for the quiz
     * Auto-generated by the database
     */
    @PrimaryGeneratedColumn()
    id!: number;

    /**
     * Quiz name/title (e.g., "Epic 40-Team Mock Championship 2025")
     * Displayed in UI headers and navigation
     */
    @Column()
    name!: string;

    /**
     * Score Scale Conversion Feature
     * 
     * When enabled, converts scores from different round scales to a standard scale
     * Example: Round 1 has max 20 points, Round 2 has max 10 points
     *          With standardScale=10, both are normalized to /10 for fair comparison
     * 
     * Default: false (disabled)
     */
    @Column({ default: false })
    scaleConversionEnabled!: boolean;

    /**
     * Standard Scale Value
     * 
     * The target scale to convert all round scores to when scaleConversionEnabled=true
     * Example: standardScale=10 means all rounds normalized to /10
     * 
     * Optional: null when scaleConversionEnabled=false
     */
    @Column({ type: 'float', nullable: true })
    standardScale?: number;

    /**
     * Gradient Color Feature
     * 
     * When enabled, teams are colored with a gradient from green (1st) to red (last)
     * When disabled, all teams get the same color
     * 
     * Default: true (enabled)
     * Used in: Scoreboard and ChartView components
     */
    @Column({ default: true })
    gradientEnabled!: boolean;

    /**
     * Quiz creation timestamp
     * Automatically set by TypeORM when quiz is created
     * Used for: Sorting quizzes by date, displaying quiz history
     */
    @CreateDateColumn()
    creationDate!: Date;

    /**
     * All rounds (questions/categories) in this quiz
     * 
     * Cascade: When quiz is deleted, all rounds are automatically deleted
     * OnDelete CASCADE: Database-level cascade for referential integrity
     */
    @OneToMany(() => Round, round => round.quiz, { cascade: true, onDelete: 'CASCADE' })
    rounds!: Round[];

    /**
     * All team participations in this quiz
     * 
     * Junction table entries containing:
     * - Team reference
     * - Quiz-specific team number (order/position)
     * - All scores for this team in this quiz
     * 
     * Cascade: When quiz is deleted, all team participations are automatically deleted
     */
    @OneToMany(() => TeamQuiz, teamQuiz => teamQuiz.quiz, { cascade: true, onDelete: 'CASCADE' })
    teamQuizzes!: TeamQuiz[];
}