/**
 * Team Entity
 * 
 * Purpose: Represents a reusable team that can participate in multiple quizzes.
 * 
 * Architecture Note:
 * - Teams are "global" entities - same team can be used across different quizzes
 * - Team numbering (position/order) is stored in TeamQuiz junction table, NOT here
 * - This allows the same team to have different numbers in different quizzes
 * 
 * Relationships:
 * - One team can participate in many quizzes (via TeamQuiz junction table)
 * 
 * Database Table: "team"
 */

import { Entity, PrimaryGeneratedColumn, Column, OneToMany } from "typeorm";
import { TeamQuiz } from "./TeamQuiz";

@Entity()
export class Team {
    /**
     * Primary key - unique identifier for the team
     * Auto-generated by the database
     */
    @PrimaryGeneratedColumn()
    id!: number;

    /**
     * Team name (e.g., "The Champions", "Quiz Masters", "Team A")
     * Required field - cannot be null
     */
    @Column()
    name!: string;

    /**
     * All quiz participations for this team
     * Each TeamQuiz entry represents this team's participation in a specific quiz
     * Includes quiz-specific data like team number and scores
     */
    @OneToMany(() => TeamQuiz, teamQuiz => teamQuiz.team)
    teamQuizzes!: TeamQuiz[];
}